version: '3'

tasks:
  default:
    cmds:
      - task: gitconfig

  clean:
    cmds:
      - task: gitconfig:clean

  gitconfig:
    desc: Create gitconfig symlink
    cmds:
      - |
        if [ -f "~/.gitconfig" -a ! -L "~/.gitconfig" ]; then
          mv ~/.gitconfig ~/.gitconfig.local
        fi
      - printf "{{ .YELLOW }}Set your user info to '~/.gitconfig.local'{{ .RESET }}"
      - stow -t ~ --ignore=".*\.fish" --ignore="Taskfile.yml" git

  gitconfig:clean:
    desc: Clean gitconfig
    cmds:
      - stow -t ~ -D git
