version: '3'

vars:
  YELLOW:
    sh: tput setaf 226
  RESET:
    sh: tput sgr0
  DOTFILE_DIR:
    sh: pwd

includes:
  homebrew:
    taskfile: ./homebrew/Taskfile.yml
  tmux:
    taskfile: ./tmux/Taskfile.yml

tasks:
  build:
    desc: Build dotfiles
    cmds:
      - task: homebrew
      - task: tmux

  clean:
    cmds:
      - task: homebrew:clean
      - task: tmux:clean
