version: '3'

vars:
  YELLOW:
    sh: tput setaf 226
  RESET:
    sh: tput sgr0
  DOTFILE_DIR:
    sh: pwd

includes:
  homebrew:
    taskfile: ./homebrew/Taskfile.yml
  bash:
    taskfile: ./bash/Taskfile.yml
  fish:
    taskfile: ./fish/Taskfile.yml
  git:
    taskfile: ./git/Taskfile.yml
  starship:
    taskfile: ./starship/Taskfile.yml
  hikizanemacs:
    taskfile: ./hikizanemacs/Taskfile.yml
  wsl:
    taskfile: ./wsl/Taskfile.yml

tasks:
  build:
    desc: Build dotfiles
    cmds:
      - task: homebrew
      - task: bash
      - task: fish
      - task: git
      - task: starship
      - task: hikizanemacs
      - task: wsl

  clean:
    cmds:
      - task: wsl:clean
      - task: hikizanemacs:clean
      - task: starship:clean
      - task: git:clean
      - task: fish:clean
      - task: bash:clean
      - task: homebrew:clean
