version: '3'

vars:
  YELLOW:
    sh: tput setaf 226
  RESET:
    sh: tput sgr0
  DOTFILE_DIR:
    sh: pwd

includes:
  homebrew:
    taskfile: ./homebrew/Taskfile.yml
  bash:
    taskfile: ./bash/Taskfile.yml
  fish:
    taskfile: ./fish/Taskfile.yml
  tmux:
    taskfile: ./tmux/Taskfile.yml
  git:
    taskfile: ./git/Taskfile.yml
  starship:
    taskfile: ./starship/Taskfile.yml
  doomemacs:
    taskfile: ./doomemacs/Taskfile.yml
  tmuxinator:
    taskfile: ./tmuxinator/Taskfile.yml
  wsl:
    taskfile: ./wsl/Taskfile.yml
  ollama:
    taskfile: ./ollama/Taskfile.yml
  miniconda:
    taskfile: ./miniconda/Taskfile.yml

tasks:
  build:
    desc: Build dotfiles
    cmds:
      - task: homebrew
      - task: bash
      - task: fish
      - task: tmux
      - task: git
      - task: starship
      - task: doomemacs
      - task: tmuxinator
      - task: ollama
      - task: miniconda
      - task: wsl

  clean:
    cmds:
      - task: wsl:clean
      - task: ollama:clean
      - task: miniconda:clean
      - task: tmuxinator:clean
      - task: doomemacs:clean
      - task: starship:clean
      - task: git:clean
      - task: tmux:clean
      - task: fish:clean
      - task: bash:clean
      - task: homebrew:clean
