version: '3'

vars:
  YELLOW:
    sh: tput setaf 226
  RESET:
    sh: tput sgr0
  DOTFILE_DIR:
    sh: pwd

includes:
  homebrew:
    taskfile: ./homebrew/Taskfile.yml
  tmux:
    taskfile: ./tmux/Taskfile.yml
  fish:
    taskfile: ./fish/Taskfile.yml
  git:
    taskfile: ./git/Taskfile.yml
  doomemacs:
    taskfile: ./doomemacs/Taskfile.yml
  wsl:
    taskfile: ./wsl/Taskfile.yml

tasks:
  build:
    desc: Build dotfiles
    cmds:
      - task: homebrew
      - task: tmux
      - task: fish
      - task: git
      - task: doomemacs
      - task: wsl

  clean:
    cmds:
      - task: homebrew:clean
      - task: tmux:clean
      - task: fish:clean
      - task: git:clean
      - task: doomemacs:clean
      - task: wsl:clean
