name: default
root: ~

windows:
  - base:
      layout: main-horizontal
      panes:
        - emacs --daemon
  - dotfiles:
      layout: main-horizontal
      panes:
        - cd ~/.dotfiles
  - ollama:
      layout: main-horizontal
      panes:
        - ollama start
