name: default
root: ~

windows:
  - emacs:
      layout: main-horizontal
      panes:
        - emacs:
          - ~/.config/emacs/bin/doom env
          - if ! procs emacs --no-header | tr -s " " | cut -d " " -f 10 | rg -q "emacs"; emacs -nw; end
