name: project
root: <%= @args[0] %>

windows:
  - org:
      layout: main-horizontal
      panes:
        - emacs:
            - e
        - fish
  - editor:
      layout: main-horizontal
      panes:
        - emacs:
            - e .
        - fish
