name: project
root: <%= @args[0] %>

windows:
  - org:
      layout: main-horizontal
      panes:
        - emacs:
            - e -e '(progn (+workspace/rename "org-<%= File.basename(@args[0])%>") (org-open-today))'
  - project:
      layout: main-horizontal
      panes:
        - emacs:
            - e -e '(progn (+workspace/rename "<%= File.basename(@args[0])%>") (find-file "<%= @args[0] %>"))'
        - pwd
