version: '3'

tasks:
  default:
    cmds:
      - task: config
      - task: completion

  clean:
    cmds:
      - task: completion:clean
      - task: config:clean

  config:
    desc: Create config symlinks
    cmds:
      - mkdir -p ~/.config/tmuxinator
      - stow -R -t ~/.config/tmuxinator --ignore="Taskfile.yml" --ignore=".*\.fish" tmuxinator

  config:clean:
    desc: Clean config
    cmds:
      - stow -t ~ -D tmuxinator

  completion:
    desc: Setup completion (https://github.com/tmuxinator/tmuxinator?tab=readme-ov-file#fish)
    cmds:
      - wget https://raw.githubusercontent.com/tmuxinator/tmuxinator/master/completion/tmuxinator.fish -O ~/.config/fish/completions/tmuxinator.fish

  completion:clean:
    desc: Clean completion
    cmds:
      - rm ~/.config/fish/completions/tmuxinator.fish
