version: '3'

tasks:
  default:
    cmds:
      - task: config

  clean:
    cmds:
      - task: config:clean

  config:
    cmds:
      - mkdir -p ~/.emacs.vanilla
      - stow -R -t ~/.emacs.vanilla --ignore=".*\.fish" --ignore="Taskfile.yml" vanillaemacs

  config:clean:
    cmds:
      - stow -t ~ -D vanillaemacs
