version: '3'

tasks:
  default:
    cmds:
      - task: config

  clean:
    cmds:
      - task: config:clean

  config:
    cmds:
      - stow -R -t ~/.emacs.default/.emacs.d --ignore=".*\.fish" --ignore="Taskfile.yml" vanillaemacs

  config:clean:
    cmds:
      - stow -t ~ -D vanillaemacs
