version: '3'

tasks:
  default:
    cmds:
      - task: install

  clean:
    desc: Clean miniconda
    cmds:
      - rm -rf ~/miniconda3

  install:
    desc: Install miniconda
    cmds:
      - |
        mkdir -p ~/miniconda3
        wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda3/miniconda.sh
        bash ~/miniconda3/miniconda.sh -b -u -p ~/miniconda3
        rm -rf ~/miniconda3/miniconda.sh
