version: '3'

tasks:
  default:
    cmds:
      - task: chemacs2
      - task: emacs-profiles

  clean:
    cmds:
      - task: emacs-profiles:clean
      - task: chemacs2:clean

  chemacs2:
    cmds:
      - |
        if [ ! -f ~/.emacs.d/chemacs.el ]; then
          [ -f ~/.emacs ] && mv ~/.emacs ~/.emacs.bak
          [ -d ~/.emacs.d ] && mv ~/.emacs.d ~/.emacs.default
          git clone https://github.com/plexus/chemacs2.git ~/.emacs.d
          mkdir -p ~/.emacs.sandbox
        fi

  chemacs:clean:
    cmds:
      - |
        [ -d ~/.emacs.default ] && mv ~/.emacs.default ~/.emacs.d

  emacs-profiles:
    cmds:
      - stow -R -t ~ --ignore=".*\.fish" --ignore="Taskfile.yml" chemacs2

  emacs-profiles:clean:
    cmds:
      - stow -t ~ -D chemacs2
