version: '3'

tasks:
  default:
    cmds:
      - task: config
      - task: font

  clean:
    cmds:
      - echo 'do nothing'

  config:
    desc: Copy configs
    platforms: [linux]
    cmds:
      - |
        if uname -r | grep -q "microsoft"; then
          bash -c "{{ .DOTFILE_DIR }}/wsl/setup_wsl.el"
        fi

  font:
    desc: Copy font configs
    platforms: [linux]
    cmds:
      - "{{ .DOTFILE_DIR }}/wsl/setup_wslg_font"
