version: '3'

tasks:
  default:
    cmds:
      - task: config
      - task: wslu

  clean:
    cmds:
      - echo 'do nothing'

  config:
    desc: Copy configs
    platforms: [linux]
    cmds:
      - |
        if uname -r | grep -q "microsoft"; then
          bash -c "./script/setup_wsl.el"
        fi

  wslu:
    desc: Install wslu
    platforms: [linux]
    cmds:
      - |
        if uname -r | grep -q "microsoft"; then
          sudo apt install -y gnupg2 apt-transport-https
          if [ ! -e "/usr/share/keyrings/wslu-archive-keyring.pgp" ]; then
            wget -O - https://pkg.wslutiliti.es/public.key | sudo gpg -o /usr/share/keyrings/wslu-archive-keyring.pgp --dearmor
          fi
          if [ ! -e "/etc/apt/sources.list.d/wslu.list" ]; then
            echo "deb [signed-by=/usr/share/keyrings/wslu-archive-keyring.pgp] https://pkg.wslutiliti.es/kali kali-rolling main" | sudo tee -a /etc/apt/sources.list.d/wslu.list
          fi
          sudo apt update
          sudo apt install -y wslu
        fi
