version: '3'

tasks:
  default:
    cmds:
      - task: brewfile
      - task: bundle

  clean:
    desc: Clean homebrew
    cmds:
      - task: brewfile:clean

  brewfile:
    desc: Create symlink
    cmds:
      - stow -t ~ --ignore=".*\.fish" --ignore=".*\.bash" --ignore="Taskfile.yml" homebrew
    sources:
      - ./homebrew/.brewfile

  brewfile:clean:
    desc: Clean brewfile
    cmds:
      - stow -t ~ -D homebrew

  bundle:
    desc: Brew bundle
    cmds:
      - cmd: |
          if [ -d "~/.linuxbrew" ]; then
            eval "$(~/.linuxbrew/bin/brew shellenv)"
          fi
        platforms: [linux]
      - cmd: |
          if [ -d "/home/linuxbrew/.linuxbrew" ]; then
            eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          fi
        platforms: [linux]
      - brew bundle --file "./homebrew/.brewfile"
