version: '3'

tasks:
  default:
    cmds:
      - task: brewfile
      - task: bundle

  clean:
    desc: Clean homebrew
    cmds:
      - rm "~/.brewfile"

  brewfile:
    desc: Create symlink
    cmds:
      - |
        if [ -e "~/.brewfile" -a ! -L "~/.brewfile" ]; then
          mv "~/.brewfile" "~/.brewfile.bak"
        fi
      - ln -s "{{ .DOTFILE_DIR }}/homebrew/brewfile" "~/.brewfile"
    sources:
      - ./homebrew/brewfile

  bundle:
    desc: Brew bundle
    cmds:
      - cmd: |
          if [ -d "~/.linuxbrew" ]; then
            eval "$(~/.linuxbrew/bin/brew shellenv)"
          fi
        platforms: [linux]
      - cmd: |
          if [ -d "/home/linuxbrew/.linuxbrew" ]; then
            eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          fi
        platforms: [linux]
      - brew bundle --file "./homebrew/brewfile"
