version: '3'

tasks:
  default:
    cmds:
      - task: config

  clean:
    cmds:
      - task: config:clean

  config:
    cmds:
      - stow -R -t ~ --ignore=".*\.fish" --ignore="Taskfile.yml" hikizanemacs

  config:clean:
    cmds:
      - stow -t ~ -D hikizanemacs
