version: '3'

tasks:
  default:
    cmds:
      - task: emacs-mozc
      - task: doom
      - task: doom-d
      - task: doom:upgrade
      - task: doom:sync

  clean:
    cmds:
      - task: doom-d:clean
      - task: doom:clean

  doom:
    cmds:
      - |
        if [ ! -d ~/.config/emacs ]; then
          git clone --depth 1 https://github.com/doomemacs/doomemacs ~/.config/emacs
          ~/.config/emacs/bin/doom install
        fi

  doom:clean:
    desc: uninstall doom
    cmds:
      - rm -rf ~/.config/emacs

  doom-d:
    desc: Create doom.d symlink
    cmds:
      - stow -R -t ~ --ignore=".*\.bash" --ignore=".*\.fish" --ignore="Taskfile.yml" doomemacs

  doom-d:clean:
    desc: Clean doom.d symlink
    cmds:
      - stow -t ~ -D doomemacs

  doom:upgrade:
    cmds:
      - fish -c "~/.config/emacs/bin/doom upgrade"

  doom:sync:
    cmds:
      - fish -c "~/.config/emacs/bin/doom sync"

  emacs-mozc:
    desc: Install emacs-mozc
    cmds:
      - cmd: if ! apt search "^emacs-mozc$" | grep -q "installed"; then sudo apt install -y emacs-mozc; fi
        platforms: [linux]
